---
swagger: "2.0"
info:
  description: "VMs manager at peak hours"
  version: "1.0.0"
  title: "Openstack VMs manager"
host: "172.16.3.42:8080"
basePath: "/v1"
tags:
- name: "images"
  description: "Images collection"
- name: "flavors"
  description: "Flavors collection"
- name: "networks"
  description: "Networks collection"
- name: "servers"
  description: "Servers collection"
- name: "schedules"
  description: "Schedules collection"
schemes:
- "http"
paths:
  /images:
    get:
      tags:
      - "images"
      summary: "Get images"
      description: "Get all images available in the system"
      operationId: "get_images"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              type: "object"
              properties: {}
      x-swagger-router-controller: "swagger_server.controllers.images_controller"
  /flavors:
    get:
      tags:
      - "flavors"
      summary: "Get flavors"
      description: "Get all flavors available in the system"
      operationId: "get_flavors"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              type: "object"
              properties: {}
      x-swagger-router-controller: "swagger_server.controllers.flavors_controller"
  /networks:
    get:
      tags:
      - "networks"
      summary: "Get networks"
      description: "Get all networks"
      operationId: "get_networks"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              type: "object"
              properties: {}
      x-swagger-router-controller: "swagger_server.controllers.networks_controller"
  /servers:
    get:
      tags:
      - "servers"
      summary: "Get servers"
      description: "Get all servers running in the system"
      operationId: "get_servers"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              type: "object"
              properties: {}
      x-swagger-router-controller: "swagger_server.controllers.servers_controller"
  /schedules:
    get:
      tags:
      - "schedules"
      summary: "Get schedules"
      description: "Returns all schedules"
      operationId: "get_schedules"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Schedule"
      x-swagger-router-controller: "swagger_server.controllers.schedules_controller"
    post:
      tags:
      - "schedules"
      summary: "Create a new schedule"
      description: ""
      operationId: "add_schedule"
      consumes:
      - "application/json"
      produces:
      - "plain/text"
      parameters:
      - in: "body"
        name: "body"
        description: "Schedule data"
        required: true
        schema:
          $ref: "#/definitions/Schedule"
      responses:
        "201":
          description: "Created"
          schema:
            type: "string"
            example: "34d72378-a3f0-11ea-8eb6-001dd8b7258f"
        "400":
          description: "Bad json format"
      x-swagger-router-controller: "swagger_server.controllers.schedules_controller"
  /schedules/{scheduleId}:
    delete:
      tags:
      - "schedules"
      summary: "Deletes a schedule"
      description: ""
      operationId: "delete_schedule"
      produces:
      - "plain/text"
      parameters:
      - name: "scheduleId"
        in: "path"
        description: "Schedule ID to delete"
        required: true
        type: "string"
      responses:
        "200":
          description: "Deleted"
        "404":
          description: "Schedule not found"
      x-swagger-router-controller: "swagger_server.controllers.schedules_controller"
definitions:
  Schedule:
    type: "object"
    required:
    - "peak_interval"
    - "server"
    properties:
      id:
        type: "string"
        example: "34d72378-a3f0-11ea-8eb6-001dd8b7258f"
      peak_interval:
        type: "object"
        allOf:
        - $ref: "#/definitions/PeakInterval"
      server:
        type: "object"
        allOf:
        - $ref: "#/definitions/Server"
    example:
      server: ""
      id: "34d72378-a3f0-11ea-8eb6-001dd8b7258f"
      peak_interval: ""
  PeakInterval:
    type: "object"
    required:
    - "end"
    - "start"
    properties:
      start:
        type: "string"
        example: "6:00"
      end:
        type: "string"
        example: "7:00"
  Server:
    type: "object"
    required:
    - "count"
    - "flavor"
    - "image"
    - "network"
    properties:
      image:
        type: "string"
        example: "Cirros"
      flavor:
        type: "string"
        example: "basic"
      network:
        type: "string"
        example: "internal"
      count:
        type: "integer"
        format: "int64"
        example: 1
