# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Server(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, image: str=None, flavor: str=None, network: str=None, count: int=None):  # noqa: E501
        """Server - a model defined in Swagger

        :param name: The name of this Server.  # noqa: E501
        :type name: str
        :param image: The image of this Server.  # noqa: E501
        :type image: str
        :param flavor: The flavor of this Server.  # noqa: E501
        :type flavor: str
        :param network: The network of this Server.  # noqa: E501
        :type network: str
        :param count: The count of this Server.  # noqa: E501
        :type count: int
        """
        self.swagger_types = {
            'name': str,
            'image': str,
            'flavor': str,
            'network': str,
            'count': int
        }

        self.attribute_map = {
            'name': 'name',
            'image': 'image',
            'flavor': 'flavor',
            'network': 'network',
            'count': 'count'
        }

        self._name = name
        self._image = image
        self._flavor = flavor
        self._network = network
        self._count = count

    @classmethod
    def from_dict(cls, dikt) -> 'Server':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Server of this Server.  # noqa: E501
        :rtype: Server
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Server.


        :return: The name of this Server.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Server.


        :param name: The name of this Server.
        :type name: str
        """

        self._name = name

    @property
    def image(self) -> str:
        """Gets the image of this Server.


        :return: The image of this Server.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image: str):
        """Sets the image of this Server.


        :param image: The image of this Server.
        :type image: str
        """
        if image is None:
            raise ValueError("Invalid value for `image`, must not be `None`")  # noqa: E501

        self._image = image

    @property
    def flavor(self) -> str:
        """Gets the flavor of this Server.


        :return: The flavor of this Server.
        :rtype: str
        """
        return self._flavor

    @flavor.setter
    def flavor(self, flavor: str):
        """Sets the flavor of this Server.


        :param flavor: The flavor of this Server.
        :type flavor: str
        """
        if flavor is None:
            raise ValueError("Invalid value for `flavor`, must not be `None`")  # noqa: E501

        self._flavor = flavor

    @property
    def network(self) -> str:
        """Gets the network of this Server.


        :return: The network of this Server.
        :rtype: str
        """
        return self._network

    @network.setter
    def network(self, network: str):
        """Sets the network of this Server.


        :param network: The network of this Server.
        :type network: str
        """
        if network is None:
            raise ValueError("Invalid value for `network`, must not be `None`")  # noqa: E501

        self._network = network

    @property
    def count(self) -> int:
        """Gets the count of this Server.


        :return: The count of this Server.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count: int):
        """Sets the count of this Server.


        :param count: The count of this Server.
        :type count: int
        """
        if count is None:
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count
